trigger:
- bla

pool:
    vmImage: 'windows-latest'

steps:


- task: DownloadSecureFile@1
  inputs:
    secureFile: 'FileFinder.aab'
  name: app

- task: Build-2Secure@0
  inputs:
    Platform: 'android'
    Sign: 'privateSigning'
    App: '$(app.secureFilePath)'
    Token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzk5MTY5NDAtMWJmZS0xMWVlLWI4NzItOWJkZTg0M2QyYmUyIiwic2FsdCI6IjkyOTI0NjRhLWY4MTUtNDA5Zi05NGJiLTE5MTFjMWZiNTFmMCJ9.D1ywWh1K6pabwdFEJTMyd6BA1nBlIDKMvGEGQG976io'
    FusionSetId: 'd2574330-5856-11ee-800b-a111bd4d22d3'
    SigningFingerprint: '8DF593C1B6EAA6EADADCE36831FE82B08CAC8D74'
    OutputFileName: "secureduniversal"
    BuildToTest: 'firebase'
  name: 'buildTask'

- script: |
   echo "Built APK file: $(buildTask.AppDomeSecuredApp)"\
   echo "dir: $(buildTask.AppdomeOutputsDir)"


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(buildTask.AppDomeSecuredApp)'
    ArtifactName: 'Appdome Output'   

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(buildTask.AppdomeOutputsDir)'
    ArtifactName: 'Appdome Output1'   


